### ISSUE TITLE
someValuesFrom vs. allValuesFrom

### ISSUE THREAD

**Issue by laurianvm** [MareGraph-EU/assets#5]
I don't know how to interpret the restrictions on the :hasArea property in the Distribution class:
'someValuesFrom' (https://github.com/MareGraph-EU/assets/blob/main/ontologies/distribution/latest/distribution.ttl#L233)
but then also 'allValuesFrom' (https://github.com/MareGraph-EU/assets/blob/main/ontologies/distribution/latest/distribution.ttl#L249)
Does the later make the first redundant?

Came across the similar statements in attribute-trait:
https://github.com/MareGraph-EU/assets/blob/main/ontologies/attribute-trait/latest/attribute-trait.ttl#L227 and 
https://github.com/MareGraph-EU/assets/blob/main/ontologies/attribute-trait/latest/attribute-trait.ttl#L231

**Comment by giorgialodi** [comment]
No it means that it should have at least one value and the value is only of the type Distribution. It is perfectly possible frome a semantic perspective :)

**Comment by laurianvm** [comment]
Aha yes, I see now :)
so the corresponding SHACL-shape will require both a sh:class and sh:minCount
thanks for explaining!

**Comment by giorgialodi** [comment]
Exactly! :-)
